# -*- coding: utf-8 -*-
"""RileyBrown_Cerebro_rag_guide.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ryWadqt07Q38MJmXUS64ywq-Eyn-nnHR

# Cerebro RAG System

**Retrieval-Augmented Generation (RAG)** lets an LLM answer questions using your own documents — without retraining.

### How RAG works:
```
User Question → Embed Question → Find Similar Docs → LLM answers with context
```

---

## Step 0: Install Dependencies
"""

!pip install sentence-transformers faiss-cpu openai numpy --quiet

"""## Step 1: Create Your Knowledge Base

In a real system, these would be loaded from PDFs, databases, or websites.
Here we use a hand-crafted corpus of pirate lore.
"""

# Upload your corpus files to Colab
# Option 1: Upload manually
from google.colab import files
import os

# Create the directory
os.makedirs("corpus/socrates", exist_ok=True)

# This will open a file picker — select ALL your .txt files
uploaded = files.upload()

# Move them into the folder
for filename in uploaded:
    os.rename(filename, f"corpus/socrates/{filename}")

print(f"✅ Uploaded {len(uploaded)} files")

import os

corpus_dir = "corpus/socrates"
documents = []
doc_id = 0

for filename in sorted(os.listdir(corpus_dir)):
    if not filename.endswith(".txt"):
        continue

    with open(os.path.join(corpus_dir, filename), "r", encoding="utf-8") as f:
        raw_text = f.read()

    # Split into chunks by double newline (paragraph-level)
    # This roughly preserves dialogue exchanges
    paragraphs = [p.strip() for p in raw_text.split("\n\n") if p.strip()]

    # Group small paragraphs together into ~500 word chunks
    current_chunk = ""
    for para in paragraphs:
        if len((current_chunk + "\n\n" + para).split()) > 500 and current_chunk:
            documents.append({
                "id": f"doc_{doc_id:04d}",
                "title": filename.replace(".txt", "").replace("_", " ").title(),
                "text": current_chunk.strip()
            })
            doc_id += 1
            current_chunk = para
        else:
            current_chunk += "\n\n" + para if current_chunk else para

    # Don't forget the last chunk
    if current_chunk.strip():
        documents.append({
            "id": f"doc_{doc_id:04d}",
            "title": filename.replace(".txt", "").replace("_", " ").title(),
            "text": current_chunk.strip()
        })
        doc_id += 1

print(f"✅ Loaded {len(documents)} chunks from {len(os.listdir(corpus_dir))} files")
for doc in documents[:10]:
    print(f"  [{doc['id']}] {doc['title']} ({len(doc['text'].split())} words)")
print(f"  ... and {len(documents) - 10} more" if len(documents) > 10 else "")

"""## Step 2: Embed Documents

We convert each text chunk into a **vector** (a list of numbers) that captures its semantic meaning.
Similar texts will have vectors that point in similar directions.
"""

from sentence_transformers import SentenceTransformer
import numpy as np

# Load a small, fast embedding model (downloads ~90MB on first run)
print("Loading embedding model...")
embedder = SentenceTransformer('all-MiniLM-L6-v2')

# Embed all documents
texts = [doc['text'] for doc in documents]
embeddings = embedder.encode(texts, show_progress_bar=True)

print(f"\n✅ Embedded {len(embeddings)} documents")
print(f"   Each embedding is a vector of {embeddings.shape[1]} dimensions")
print(f"   Embedding matrix shape: {embeddings.shape}")

"""## Step 3: Build a Vector Index

**FAISS** (Facebook AI Similarity Search) creates an index that lets us find the nearest neighbor vectors in milliseconds — even with millions of documents.
"""

import faiss

# Build a flat L2 (Euclidean distance) index
# For large corpora, use faiss.IndexIVFFlat for speed
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)

# FAISS requires float32
embeddings_f32 = embeddings.astype('float32')
index.add(embeddings_f32)

print(f"✅ FAISS index built")
print(f"   Index type:  Flat L2 (exact search)")
print(f"   Dimensions:  {dimension}")
print(f"   Total docs:  {index.ntotal}")

"""## Step 4: Retrieval Function

Given a question, we embed it and find the most similar chunks in our index.
"""

def retrieve(query: str, k: int = 3) -> list[dict]:
    """
    Embed the query and retrieve the top-k most similar documents.
    Returns a list of document dicts with an added 'score' field.
    """
    # Embed the query
    query_vec = embedder.encode([query]).astype('float32')

    # Search the FAISS index
    distances, indices = index.search(query_vec, k)

    # Collect matching documents
    results = []
    for dist, idx in zip(distances[0], indices[0]):
        doc = documents[idx].copy()
        doc['score'] = float(dist)   # Lower = more similar
        results.append(doc)

    return results


# --- Test the retriever ---
test_queries = [
    "What is virtue and can it be taught?",
    "How did Socrates defend himself at trial?",
    "What happens to the soul after death?"
]

for test_query in test_queries:
    results = retrieve(test_query, k=3)
    print(f"Query: '{test_query}'\n")
    print("Top retrieved chunks:")
    for i, r in enumerate(results, 1):
        print(f"  #{i} [{r['id']}] {r['title']} (score: {r['score']:.2f})")
        print(f"      {r['text'][:100]}...\n")
    print("-" * 60 + "\n")

"""## Step 5: The RAG Pipeline

We combine retrieval with generation: stuff the retrieved chunks into a prompt, then ask the LLM to answer using only that context.
"""

from openai import OpenAI
client = OpenAI(api_key="YOUR_API_KEY_HERE")

def build_prompt(query: str, chunks: list[dict]) -> str:
    """Build a RAG prompt: Socrates persona + retrieved context + user question."""
    context_block = "\n\n".join(
        f"[{c['title']}]\n{c['text']}" for c in chunks
    )
    return f"""You are Socrates of Athens (470–399 BC). You engage in dialogue using the Socratic method — asking probing questions to expose contradictions and deepen understanding, rather than giving direct answers.

You are conversational, ironic, playful but incisive. You use analogies and metaphors. You speak in first person as yourself.

You believe in the examined life, intellectual humility, and that virtue is knowledge. Your goal is to help the user think through their ideas, not to lecture.

Use the following passages from dialogues about your life and teachings to ground your responses. Draw on this context when relevant, but do not fabricate specific quotes or claim to have said things not found here.

=== CONTEXT ===
{context_block}
=== END CONTEXT ===

The user says: {query}"""

def rag_query(query: str, k: int = 3) -> str:
    """Full RAG pipeline: retrieve → build prompt → generate."""
    chunks = retrieve(query, k=k)
    prompt = build_prompt(query, chunks)
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
    )
    return response.choices[0].message.content

print("✅ RAG pipeline ready")

"""## Step 6: Ask Questions!"""

questions = [
    "What is virtue and can it be taught?",
    "How should I deal with someone who thinks they know everything?",
    "Is it better to suffer injustice or to commit it?",
    "What is the meaning of a good life?",
    "What are your thoughts on cryptocurrency?",  # Should show he can handle modern topics
]

for q in questions:
    print(f"🏛️  Q: {q}")
    answer = rag_query(q)
    print(f"   A: {answer}")
    print("-" * 70)

"""## Step 7: Inspect What the Model Actually Sees

Transparency is key in RAG. Here's how to show exactly which chunks were retrieved for a query.
"""

def rag_query_verbose(query: str, k: int = 3):
    """RAG with full transparency — shows retrieved chunks before generating."""
    print(f"📌 Query: {query}\n")
    chunks = retrieve(query, k=k)
    print(f"📚 Retrieved {len(chunks)} chunks:")
    for i, c in enumerate(chunks, 1):
        print(f"   {i}. [{c['id']}] {c['title']}  (L2 score: {c['score']:.2f})")
    prompt = build_prompt(query, chunks)
    print(f"\n📝 Prompt sent to LLM ({len(prompt)} chars):\n")
    print(prompt[:600] + "...\n")
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
    )
    answer = response.choices[0].message.content
    print(f"🏛️ Answer:\n{answer}")
    return answer

_ = rag_query_verbose("What is justice?")

"""## Bonus: Semantic Similarity Explorer

Visualise how query embeddings relate to document embeddings using PCA.
"""

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

query = "What is virtue and can it be taught?"
query_vec = embedder.encode([query]).astype('float32')

all_vecs = np.vstack([embeddings_f32, query_vec])
pca = PCA(n_components=2)
coords = pca.fit_transform(all_vecs)
doc_coords = coords[:-1]
q_coord = coords[-1]

fig, ax = plt.subplots(figsize=(10, 7))
ax.scatter(doc_coords[:, 0], doc_coords[:, 1], c='steelblue', s=30, zorder=3, alpha=0.5)

# Only label the top 5 nearest chunks to avoid a cluttered mess
distances, indices = index.search(query_vec, k=5)
for idx in indices[0]:
    ax.annotate(documents[idx]['title'], doc_coords[idx], fontsize=7, ha='center',
                va='bottom', xytext=(0, 8), textcoords='offset points')
    ax.scatter(doc_coords[idx, 0], doc_coords[idx, 1], c='gold', s=80, zorder=4, edgecolors='black', linewidth=0.5)

ax.scatter(*q_coord, c='crimson', marker='*', s=300, zorder=5, label='Query')
ax.annotate(f"Q: '{query}'", q_coord, fontsize=9, color='crimson',
            xytext=(6, 6), textcoords='offset points', fontweight='bold')

ax.set_title('Document Embeddings (PCA 2D) — Socrates Corpus', fontsize=13)
ax.set_xlabel('PCA Component 1')
ax.set_ylabel('PCA Component 2')
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
print("Gold dots are top 5 nearest chunks. Documents closer to the red star are retrieved first.")

"""---

## Summary & Next Steps

| Step | What we did | Production upgrade |
|------|-------------|-------------------|
| **Chunk** | Hard-coded text blocks | Load from PDFs/DBs, split by tokens |
| **Embed** | `all-MiniLM-L6-v2` | `text-embedding-3-large` or domain-specific model |
| **Index** | FAISS FlatL2 | Pinecone / Weaviate / pgvector |
| **Retrieve** | Top-k by L2 | Hybrid search (BM25 + dense) + reranker |
| **Generate** | Simple prompt | System prompt tuning, citation grounding |

### Key concepts to explore next:
- **Chunking strategies**: fixed-size, sentence, semantic, hierarchical
- **Hybrid retrieval**: combine keyword (BM25) + semantic search
- **Reranking**: use a cross-encoder to reorder retrieved chunks
- **Guardrails**: detect hallucination, verify citations
- **Evaluation**: RAGAS framework for measuring RAG quality
"""